apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-2
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: sec-ctx-demo-2
    image: registry.cn-shenzhen.aliyuncs.com/aluopy/node-hello:1.0
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false